import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#fff',
      paddingVertical: 40,
      paddingHorizontal: 20,
    },
    backButton: {
      marginTop: 16,
      marginLeft: 5,
      position: 'absolute',
      top: 40,
      left: 10,
    },
    title: {
      fontSize: 30,
      fontWeight: 'bold',
      color: '#000',
      marginTop: 62,
      marginBottom: 10,
      textAlign: 'left',
    },
    subtitle: {
      fontSize: 18,
      fontWeight: '400',
      color: '#000',
      marginBottom: 20,
      textAlign: 'left',
    },
    inputContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 2,
    },
    input: {
      height: 55,
      width: '100%',
      borderColor: '#bbb',
      borderWidth: 1,
      borderRadius: 11,
      marginBottom: 15,
      marginRight: 6,
      paddingLeft: 10,
      backgroundColor: '#fff',
      fontSize: 18,
      fontWeight: '500',
      color: '#333',
    },
    longInput: {
        height: 55,
        width: '98%',
        borderColor: '#bbb',
        borderWidth: 1,
        borderRadius: 11,
        marginTop: -10,
        marginBottom: 15,
        marginRight: 6,
        paddingLeft: 10,
        backgroundColor: '#fff',
        fontSize: 18,
        fontWeight: '500',
        color: '#333',
      },
    specialityOutput: {
        height: 55,
        width: '98%',
        borderColor: '#bbb',
        borderWidth: 1,
        borderRadius: 11,
        marginTop: 0,
        marginBottom: 20,
        marginRight: 6,
        paddingLeft: 10,
        backgroundColor: '#fff',
        fontSize: 18,
        fontWeight: '500',
        color: '#333',
        justifyContent: 'flex-end',
        alignItems: 'left',
    },
    specialitySubtitle: {
        height: 55,
        width: '100%',
        borderRadius: 11,
        marginBottom: -36,
        marginRight: 48,
        paddingLeft: -10,
        backgroundColor: 'transparent',
        fontSize: 16,
        fontWeight: '500',
        color: '#777',
        justifyContent: 'center',
        alignItems: 'left',
    },

    specialityText: {
      fontSize: 18,
      fontWeight: '400',
      color: '#000',
      marginBottom: 10,
      textAlign: 'left',
    },
    button: {
      height: 43,
      backgroundColor: '#dd0000',
      borderRadius: 25,
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 20,
    },
    buttonText: {
      color: '#fff',
      fontSize: 18,
      fontWeight: '600',
    },
    cancelButton: {
      height: 50,
      backgroundColor: 'transparent',
      borderRadius: 8,
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: 'auto',
      marginBottom: 20,
    },
    cancelButtonText: {
      color: '#dd0000',
      fontSize: 18,
      fontWeight: '600',
    },
    modalBackground: {
        position: 'absolute', 
        top: 0,
        left: 0,
        right: 0,
        backgroundColor: 'transparent',
        height: '65%',
    },
    pickerBackground: {
        position: 'absolute',
        bottom: -330,
        left: 0,
        right: 0,
        backgroundColor: '#cccccc',
        height: 330,
        justifyContent: 'flex-start',
    },
    picker: {
        position: 'absolute',
        width: '100%',
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: '#cccccc',
        height: 330,
    },
    // Error styles
    errorText: {
      color: 'red',
      fontSize: 14,
      marginBottom: 5,
      marginTop: -15,
    },
    errorInput: {
      borderColor: 'red',
      borderWidth: 1,
      borderRadius: 10,
      marginBottom: 30,
    },
  });
  
  export default styles;