import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ddd',
    paddingHorizontal: 0,
    paddingVertical: 36,
  },
  circleContainer: {
    width: 600,
    height: 550,
    borderRadius: 300,
    position: 'absolute',
    bottom: '92%',
    left: '42%',
    transform: [{ translateX: -250 }],
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
    backgroundColor: 'transparent',
    zIndex: 1,
  },
  background: {
    flex: 1,
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    position: 'relative',
    overflow: 'hidden',
  },
  image: {
    width: '80%',
    height: '80%',
    top: 120,
    left: 15,
    resizeMode: 'cover',
  },
  gradient: {
    position: 'absolute',
    top: 50,
    left: 0,
    width: '100%',
    height: '100%',
    zIndex: 0,
  },
  logo: {
    position: 'absolute',
    top: '82%',
    left: '55%',
    transform: [{ translateX: -165 }],
    width: 200,
    height: 80,
    zIndex: 0,
  },
  contentContainer: {
    flex: 1,
    justifyContent: 'center',
    width: '70%',
    marginTop: 60,
    marginLeft: 60,
    marginRight: 60,
    backgroundColor: '#ddd',
  },
  formContainer: {
    position: 'absolute',
    alignItems: 'center',
    marginTop: 30,
    backgroundColor: 'transparent',
  },
  section: {
    padding: 10,
    borderRadius: 10,
    backgroundColor: 'transparent',
  },
  sectionTitle: {
    fontSize: 26,
    color: '#333',
    marginTop: 5,
    marginBottom: 10,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  buttonContainer: {
    flexDirection: 'row',
    marginTop: 10,
    justifyContent: 'space-around',
  },
  button: {
    flex: 1,
    backgroundColor: 'transparent',
    paddingVertical: 10,
    borderRadius: 5,
    alignItems: 'center',
    marginHorizontal: 3,
    marginBottom: 20,
    position: 'relative',
  },
  buttonText: {
    color: '#bbb',
    fontSize: 18,
    fontWeight: 'bold',
  },
  buttonSelectedText: {
    color: '#ff0000',
  },
  line: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    width: '100%',
    height: 2,
    backgroundColor: '#ff0000',
    transition: 'width 0.3s ease-in-out',
  },
  activeButton: {
    borderBottomWidth: 2,
    borderBottomColor: 'red',
  },

  card: {
    backgroundColor: '#fff',
    padding: 16,
    marginVertical: 8,
    borderRadius: 8,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#ff0000',
    marginBottom: 8,
  },
  cardDetail: {
    fontSize: 15,
    color: '#000',
    marginTop: 0,
    marginBottom: 0,
  },
  cardSubtitle: {
    fontSize: 17,
    fontWeight: 'bold',
    color: '#ff0000',
    marginTop: 10,
    marginBottom: 10,
  },
  cardItem: {
    marginTop: 10,
    marginBottom: 10,
  },
  actionButton: {
    width: 120,
    backgroundColor: '#ff0000',
    paddingVertical: 8,
    borderRadius: 5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  actionButtonText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 14,
  },
  labelText: {
    fontWeight: '600',
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 25,
    borderWidth: 1,
    backgroundColor: '#ccc',
    borderColor: '#bbb',
    borderRadius: 30,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  searchIcon: {
    marginRight: 10,
  },
  searchInput: {
    flex: 1,
    height: 40,
    fontSize: 18,
    fontWeight: '600',
    paddingVertical: 10,
  }
});

export default styles;
