import { StyleSheet } from 'react-native';
import CommonStyles from './CommonStyles';

export default StyleSheet.create({
    container: {
      ...CommonStyles.container,
      flex: 1,
      marginTop: -120,
      backgroundColor: '#ddd',
    },
    circleContainer: {
        width: 600,
        height: 600,
        borderRadius: 300,
        position: 'absolute',
        bottom: '40%',
        left: '42%',
        transform: [{ translateX: -250 }],
        justifyContent: 'center',
        alignItems: 'center',
        overflow: 'hidden',
        backgroundColor: 'transparent',
        zIndex: 1,
    },
    background: {
      flex: 1,
      width: '100%',
      height: '100%',
      justifyContent: 'center',
      position: 'relative',
      overflow: 'hidden',
    },
    image: {
      width: '80%',
      height: '80%',
      top: 90,
      left: 15,
      resizeMode: 'cover',
    },
    gradient: {
      position: 'absolute',
      top: 10,
      left: 0,
      width: '100%',
      height: '100%',
      zIndex: 0,
    },
    logo: {
      position: 'absolute',
      top: '25%',
      left: '48%',
      transform: [{ translateX: -165 }],
      width: 330,
      height: 200,
      zIndex: 0,
    },
    formContainer: {
      position: 'absolute',
      top: '40%',
      left: '10%',
      right: '10%',
      zIndex: 2,
      alignItems: 'center',
      padding: 20,
      backgroundColor: '#fff',
      borderRadius: 40,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 15 },
      shadowOpacity: 0.3,
      shadowRadius: 15,
      elevation: 10,
    },
    title: {
      fontSize: 24,
      fontWeight: '600',
      color: '#000',
      marginBottom: 10,
      marginTop: 20,
    },
    button: {
      ...CommonStyles.button,
      backgroundColor: 'red',
      position: 'relative',
      width: '100%',
      borderRadius: 30,
      marginTop: 40,
    },
    buttonText: {
      color: 'white',
      fontSize: 18,
      fontWeight: 'bold',
      textAlign: 'center',
    },
  });
  