import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#ddd",
        paddingVertical: 0,
    },
         /* Imagen */
         circleContainer: {
            width: 600,
            height: 580,
            borderRadius: 300,
            position: 'absolute',
            bottom: '68%',
            left: '37%',
            transform: [{ translateX: -250 }],
            justifyContent: 'center',
            alignItems: 'center',
            overflow: 'hidden',
            backgroundColor: 'transparent',
            zIndex: 1,
          },
          background: {
            flex: 1,
            width: '100%',
            height: '100%',
            justifyContent: 'center',
            alignItems: 'center',
            position: 'relative',
            overflow: 'hidden',
          },
          image: {
            width: '80%',
            height: '80%',
            top: 120,
            left: 15,
            resizeMode: 'cover',
          },
          title: {
            fontSize: 26,
            color: '#fff',
            marginBottom: 75,
            paddingRight: 7,
            fontWeight: 'bold',
            textAlign: 'center',
            position: 'absolute',
            bottom: '10%',
            zIndex: 2,
          },
          gradient: {
            position: 'absolute',
            top: 55,
            left: 100,
            width: '100%',
            height: '100%',
            zIndex: 0,
          },
          profileImage: {
            width: 120,
            height: 120,
            borderRadius: 75,
            position: 'absolute',
            top: 150,
            left: '34%',
            zIndex: 2,
            borderWidth: 2,
            borderColor: '#aa0000',
        },
        userInfoContainer: {
            backgroundColor: 'transparent',
            marginTop: 280,
            padding: 20,
          },   
      infoContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginVertical: 15,
        borderBottomWidth: 1,  
        borderBottomColor: '#aaa', 
        paddingBottom: 10, 

      },
      value: {
        color: '#000',
        fontSize: 20,
        textAlign: 'left',
        flex: 1,
        flexShrink: 1,
        overflow: 'hidden',
      },
      icon: {
        marginRight: 20,
      },
    button: {
        backgroundColor: '#ee0000',
        paddingVertical: 13,
        marginBottom: 18,
        marginLeft: 76,
        width: 220,
        borderRadius: 30,
        alignItems: 'center',
        justifyContent: 'center',
        minWidth: 100,
    },
    buttonText: {
        color: '#fff',
        fontSize: 17,
        fontWeight: 'bold',
    },
});

export default styles;