import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    paddingVertical: 0,
  },
  /* Imagen */
  circleContainer: {
    width: 600,
    height: 580,
    borderRadius: 140,
    position: 'absolute',
    bottom: '68%',
    left: '37%',
    transform: [{ translateX: -250 }],
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
    backgroundColor: 'transparent',
    zIndex: 1,
  },
  background: {
    flex: 1,
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    overflow: 'hidden',
  },
  image: {
    width: '80%',
    height: '80%',
    top: 240,
    left: 60,
    resizeMode: 'cover',
  },
  title: {
    fontSize: 30,
    color: '#fff',
    marginBottom: 75,
    right: 240,
    fontWeight: '800',
    textAlign: 'center',
    position: 'absolute',
    bottom: '10%',
    zIndex: 2,
  },
  gradient: {
    position: 'absolute',
    top: 55,
    left: 100,
    width: '100%',
    height: '100%',
    zIndex: 0,
  },
  profileImage: {
    width: 120,
    height: 120,
    borderRadius: 75,
    position: 'absolute',
    top: 150,
    left: '34%',
    zIndex: 2,
    borderWidth: 2,
    borderColor: '#aa0000',
  },
  userInfoContainer: {
    backgroundColor: 'transparent',
    marginTop: 290,
    paddingHorizontal: 30,
  },
  infoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#ddd',
  },
  value: {
    color: '#000',
    fontSize: 16,
    fontWeight: '500',
    textAlign: 'left',
    flex: 1,
    flexShrink: 1,
    overflow: 'hidden',
    bottom: 10,
  },
  icon: {
    marginRight: 20,
    bottom: 10,
  },
  button: {
    backgroundColor: '#ee0000',
    paddingVertical: 13,
    marginBottom: 18,
    marginLeft: 76,
    width: 220,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 100,
  },
  buttonText: {
    color: '#fff',
    fontSize: 17,
    fontWeight: 'bold',
  },
  /* Botones de "Mis datos" y "Mis Planes" */
  userButtonsContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 0,
    top: 290,
    right: 0,
    width: '100%',
  },
  userButton: {
    flex: 1,
    backgroundColor: 'transparent',
    paddingVertical: 10,
    borderRadius: 5,
    alignItems: 'center',
    marginHorizontal: 3,
    position: 'relative',
  },
  userButtonText: {
    color: '#bbb',
    fontSize: 18,
    fontWeight: 'bold',
  },
  line: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    height: 2,
    backgroundColor: 'red',
  },
  /* Botón de cerrar sesión */
  logoutContainer: {
    width: '100%',
    alignItems: 'center',
  },
  logoutButton: {
    width: '88%',
    right: 20,
  },
  /* Picker */
  modalBackground: {
    position: 'absolute', 
    top: 0,
    left: 0,
    right: 0,
    backgroundColor: 'transparent',
    height: '65%',
  },
  pickerBackground: {
    position: 'absolute',
    bottom: -330,
    left: 0,
    right: 0,
    backgroundColor: '#cccccc',
    height: 330,
    justifyContent: 'flex-start',
  },
  picker: {
      position: 'absolute',
      width: '100%',
      bottom: 0,
      left: 0,
      right: 0,
      backgroundColor: '#cccccc',
      height: 300,
  },
  specialityOutput: {
    height: 55,
    top: 20,
    left: 20,
    width: '90%',
    borderColor: '#ddd',
    borderWidth: 1,
    borderRadius: 11,
    marginTop: 0,
    marginBottom: 20,
    marginRight: 6,
    paddingLeft: 10,
    backgroundColor: '#fff',
    fontSize: 18,
    fontWeight: '500',
    color: '#333',
    justifyContent: 'flex-end',
    alignItems: 'left',
  },
  specialitySubtitle: {
      height: 55,
      width: '100%',
      borderRadius: 11,
      marginBottom: -36,
      marginRight: 48,
      paddingLeft: -10,
      backgroundColor: 'transparent',
      fontSize: 16,
      fontWeight: '500',
      color: '#aaa',
      justifyContent: 'center',
      alignItems: 'left',
  },

  specialityText: {
    fontSize: 18,
    fontWeight: '400',
    color: '#000',
    marginBottom: 10,
    textAlign: 'left',
  },
  // Errores
  inputField: {
    marginBottom: 5,
  },
  errorText: {
    marginTop: -16,
    color: 'red',
    fontSize: 16,
  },
  // Datos vacios
  emptyText: {
    fontSize: 16,
    fontWeight: '500',
    color: '#333',
    marginTop: 20,
    marginBottom: 0,
  },
});

export default styles;
